StudyLogs/urls.py
"""Url patterns for StudyLogs"""
from django.urls import path
from . import views

app_name = 'StudyLogs'

urlpatterns = [
    # Home Page
    path('', views.index, name='index'),
    # Page that shows all topics
    path('topics/', views.topics, name='topics'),
    # Detail page for a single topic
    path('topic/<int:topic_id>/', views.topic, name='topic'),
    # Page for adding a new topic
    path('new_topic/', views.new_topic, name='new_topic'),
    # Pagefor adding a new entry
    path('new_entry/<int:topic_id>/', views.new_entry, name='new_entry'),
    # Page for editing an entry
    path('edit_entry/<int:entry_id>/', views.edit_entry, name='edit_entry'),
]

Suggestion/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('StudyLogs.urls')),
    path('users/', include('users.urls')),
]

users/urls.py
"""Url patterns for users."""

from django.urls import path, include
from . import views

app_name = 'users'
urlpatterns = [
    # include default auth urls.
    path('', include('django.contrib.auth.urls')),
    # Register
    path('register/', views.register, name='register'),
]

StudyLogs/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Topic(models.Model):
    """A topic a user is learning about."""
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)


    def __str__(self):
        """Return a string representation of the model."""
        return self.text


class Entry(models.Model):
    """Something specific learned about a topic."""
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'entries'

    def __str__(self):
        """Return string represntation of the model."""
        return f'{self.text[:50]} ...'

users/models.py
from django.db import models

# Create your models here.

StudyLogs/forms.py
from django import forms
from . models import Topic, Entry


class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text']
        labels = {'text': ''}


class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text': ''}
        widgets = {'text': forms.Textarea(attrs={'cols': 50})}

StudyLogs/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.http import Http404

import StudyLogs
from . models import Topic, Entry
from . forms import TopicForm, EntryForm

# Create your views here.

def index(request):
    """Home page for StudyLog."""
    return render(request, 'StudyLogs/index.html')

@login_required
def topics(request):
    """Show all topics."""
    # Restricting access to appropriate users.
    topics = Topic.objects.filter(owner=request.user).order_by('date_added')
    context = {'topics': topics}
    return render(request, 'StudyLogs/topics.html', context)

@login_required
def topic(request, topic_id):
    """Show a single topic and all it's entries."""
    topic = Topic.objects.get(id=topic_id)
    # Make sure the topic belongs to the current user.
    if topic.owner != request.user:
        raise Http404

    entries = topic.entry_set.order_by('-date_added')
    context = {'topic': topic, 'entries':entries}
    return render(request, 'StudyLogs/topic.html', context)

@login_required
def new_topic(request):
    """Add new topic."""
    if request.method != 'POST':
        # No data submitted; create a blank form.
        form = TopicForm()
    else:
        # Post data submitted; process data.
        form = TopicForm(data=request.POST)
        if form.is_valid():
            new_topic = form.save(commit=False)
            new_topic.owner = request.user
            new_topic.save()
            return redirect('StudyLogs:topics')

    # Display blank or invalid form.
    context = {'form': form}
    return render(request, 'StudyLogs/new_topic.html', context)

@login_required
def new_entry(request, topic_id):
    """Add a new entry for aparticular topic."""
    topic = Topic.objects.get(id=topic_id)

    if request.method != 'POST':
        # No data submitted; create a blank form
        form = EntryForm()
    else:
        # Post data submitted; process data.
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            return redirect('StudyLogs:topic', topic_id=topic_id)

    # Display blank or invalid form
    context = {'topic': topic, 'form': form}
    return render(request, 'StudyLogs/new_entry.html', context)

@login_required
def edit_entry(request, entry_id):
    """Edit an existing entry."""
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic
    if topic.owner != request.user:
        raise Http404

    if request.method != 'POST':
        # Initial request; pre-fill form with the current entry
        form = EntryForm(instance=entry)
    else:
        # Post data submitted; process data
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('StudyLogs:topic', topic_id=topic.id)

    context = {'entry': entry, 'topic': topic, 'form': form}
    return render(request, 'StudyLogs/edit_entry.html', context)

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm

# Create your views here.
def register(request):
    """Register new user."""
    if request.method != 'POST':
        """Display blank registration form."""
        form = UserCreationForm()
    else:
        """Process completed form."""
        form = UserCreationForm(data=request.POST)

        if form.is_valid():
            new_user = form.save()
            # Log user in and redirect to home page.
            login(request, new_user)
            return redirect('StudyLogs:index')

    # Display blank or invalid form.
    context = {'form': form}
    return render(request, 'registration/register.html', context)

StudyLogs/templates/StudyLogs/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}
            Study Log
        {% endblock title %}
    </title>
    {% block css %}
        <link rel="stylesheet" href="{% static 'css/base.css' %}">
        <link rel="stylesheet" href="{% static 'css/index.css' %}">
        <link rel="stylesheet" href="{% static 'css/topics.css' %}">
        <link rel="stylesheet" href="{% static 'css/topic.css' %}">
        <link rel="stylesheet" href="{% static 'css/new-entry.css' %}">
        <link rel="stylesheet" href="{% static 'css/new-topic.css' %}">
        <link rel="stylesheet" href="{% static 'css/edit-entry.css' %}">
        <link rel="stylesheet" href="{% static 'css/login.css' %}">
        <link rel="stylesheet" href="{% static 'css/register.css' %}">
        <link rel="stylesheet" href="{% static 'css/logged-out.css' %}">
        {% endblock css %}
</head>
<body>
    <div class="container">
        <header class="header">
            <nav>
                <ul>
                    <li class="nav-link">
                        <a href="{% url 'StudyLogs:index' %}">Study Log</a>
                    </li class="nav-link">
                    <li class="nav-link">
                        <a href="{% url 'StudyLogs:topics' %}">Topics</a>
                    </li class="nav-link">
                    {% if user.is_authenticated %}
                        <li class="nav-link" style="float: inline-end;">Hello, {{ user.username }}.</li>
    
                    <li class="nav-link" style="float: inline-end;">
                        <a href="{% url 'users:logout' %}">Log out</a>
                    </li class="nav-link">
                    {% else %}
                    <li class="nav-link" style="float: inline-end;">
                        <a href="{% url 'users:register' %}">Register</a>
                    </li class="nav-link">
                    <li class="nav-link" style="float: inline-end;">
                        <a href="{% url 'users:login' %}">Log in</a>
                    </li class="nav-link">
                    {% endif %}
                </ul>
            </nav>
        </header>
        <aside class="aside">
            {% block aside %}
                <p>
                    <a href="{% url 'StudyLogs:topics' %}" class="topics">Topics</a>
                </p>
            {% endblock aside %}
        </aside>
        <article class="article">{% block content%}{% endblock content %}</article>
        <footer class="footer">All rights reserver &copy; 2022, Xessive Observer</footer>
    </div>
</body>
</html>

StudyLogs/templates/StudyLogs/edit_entry.html
{% extends 'StudyLogs/base.html' %}

{% block content %}
    <p class="edit-entry">
        <a href="{% url 'StudyLogs:topic' topic.id %}">{{ topic }}</a>
    </p>

    <hr>

    <p class="edit-entry-lable">
        Edit entry:
    </p>

    <form action="{% url 'StudyLogs:edit_entry' entry.id %}" method="POST" class="form">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="save-changes">Save Changes</button>
    </form>
{% endblock content %}

StudyLogs/templates/StudyLogs/index.html
{% extends 'StudyLogs/base.html' %}
{% block content %}
    <p class="intro-msg">Study Log helps you keep track of your learning, for any topic you're
    learning about.</p>
{% endblock content %}

StudyLogs/templates/StudyLogs/new_entry.html
{% extends 'StudyLogs/base.html' %}

{% block content %}
    <p class="topic-link">
        <a href="{% url 'StudyLogs:topic' topic.id %}">{{ topic }}</a>
    </p>

    <hr>

    <p class="add-new-entry-lable">
        Add new entry:
    </p>

    <form action="{% url 'StudyLogs:new_entry' topic.id %}" method="POST" class="form">
        {% csrf_token %}
        {{ form.as_p }}
        <button name="submit" class="add-entry">Add entry</button>
    </form>

{% endblock content %}

StudyLogs/templates/StudyLogs/new_topic.html
{% extends 'StudyLogs/base.html' %}

{% block content %}
    <p class="new-topic">Add new topic:</p>

    <hr>

    <form action="{% url 'StudyLogs:new_topic' %}" method="POST" class="form">
        {% csrf_token %}
        {{form.as_p}}
        <button name="submit" class="add-topic">Add topic</button>
    </form>
{% endblock content %}

StudyLogs/templates/StudyLogs/topic.html
{% extends 'StudyLogs/base.html'%}

{% block content %}

    <p class="topic">Topic: {{ topic }}</p>
    <hr>

    <p class="entries">Entries</p>
    <p class="add-new-entry">
        <a href="{% url 'StudyLogs:new_entry' topic.id %}">Add new Entry</a>
    </p>
    <ul class="entry-list">
        {% for entry in entries %}
            <li>
                <p class="date">
                    {{ entry.date_added|date:'M d, Y H:i' }}
                </p>
                <p class="entry-content">
                    {{ entry.text|linebreaks }}
                </p>
                <p class="edit-entry-link">
                    <a href="{% url 'StudyLogs:edit_entry' entry.id %}">Edit entry</a>
                </p>
            </li>
        {% empty %}
            <li class="empty">
                There are no entries for this topic yet.
            </li>
        {% endfor %}
    </ul>

{% endblock content %}

StudyLogs/templates/StudyLogs/topics.html
{% extends 'StudyLogs/base.html'%}

{% block content %}
    <p class="topics-heading">Topics</p>
    <hr>

    <ul class="topics">
        {% for topic in topics %}
        <li>
            <a href="{% url 'StudyLogs:topic' topic.id %}">{{topic}}</a>
        </li>
        {% empty %}
        <li>
            No topic has been added yet.
        </li>
        {% endfor %}
        <a href="{% url 'StudyLogs:new_topic' %}" class="add-topic-link">Add new topic</a>
    </ul>
   
{% endblock content %}